name: ci

on:
  push:
    branches:
      - "zts"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PHP_VERSION: 8.2.16-zts

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV    
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - if: contains(github.ref, 'refs/heads/release/')
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: contains(github.ref, 'refs/heads/release/')
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: temporary-build-image-${{ env.PLATFORM_PAIR }}
          target: PHPZTSBUILDER
          cache-to: type=gha,mode=max,scope=${{ env.PLATFORM_PAIR }}-base
          outputs: type=docker,dest=/tmp/${{ env.PLATFORM_PAIR }}-base.tar
      - name: Load image
        run: |
          docker load --input /tmp/${{ env.PLATFORM_PAIR }}-base.tar
          docker image ls -a
      - name: Test
        run: |
          docker run --platform ${{ matrix.platform }} --rm temporary-build-image-${{ env.PLATFORM_PAIR }} sh -c 'uname -a && php -v'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLATFORM_PAIR }}-base.tar
          path: /tmp/${{ env.PLATFORM_PAIR }}-base.tar
  build-all:
    runs-on: ubuntu-latest
    needs: build-base
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV    
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - if: contains(github.ref, 'refs/heads/release/')
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: contains(github.ref, 'refs/heads/release/')
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: temporary-build-image-${{ env.PLATFORM_PAIR }}
          cache-from: type=gha,scope=${{ env.PLATFORM_PAIR }}-base
          cache-to: type=gha,mode=max,scope=${{ env.PLATFORM_PAIR }}
          outputs: type=docker,dest=/tmp/${{ env.PLATFORM_PAIR }}.tar
      - name: Load image
        run: |
          docker load --input /tmp/${{ env.PLATFORM_PAIR }}.tar
          docker image ls -a
      - name: Test
        run: |
          docker run --platform ${{ matrix.platform }} --rm temporary-build-image-${{ env.PLATFORM_PAIR }} sh -c 'uname -a && php -v'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLATFORM_PAIR }}.tar
          path: /tmp/${{ env.PLATFORM_PAIR }}.tar          
  test:
    runs-on: ubuntu-latest
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Download ${{ matrix.platform }} artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PLATFORM_PAIR }}.tar
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/${{ env.PLATFORM_PAIR }}.tar
          docker image ls -a
      - name: Test
        run: |
          docker run --platform ${{ matrix.platform }} --rm temporary-build-image-${{ env.PLATFORM_PAIR }} sh -c 'uname -a && php -v'
  use:
      runs-on: ubuntu-latest
      needs: build-all
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Download amd64 artifact
          uses: actions/download-artifact@v4
          with:
            name: linux-amd64.tar
            path: /tmp
        - name: Download arm64 artifact
          uses: actions/download-artifact@v4
          with:
            name: linux-arm64.tar
            path: /tmp
        - name: Load image
          run: |
            docker load --input /tmp/linux-arm64.tar
            docker load --input /tmp/linux-amd64.tar
            docker image ls -a          
        - name: Test am64
          run: |
            docker run --platform linux/amd64 --rm temporary-build-image-linux-amd64 sh -c 'uname -a && php -v'
        - name: Log into registry ${{ env.REGISTRY }}
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v3.0.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Extract Docker metadata
          id: meta
          uses: docker/metadata-action@v5.5.1
          with:
            tags: |
               type=raw,value=${{ env.PHP_VERSION }}
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v5.1.0
          with:
            context: .
            platforms: linux/amd64,linux/arm64
            provenance: false
            cache-from: |
              type=gha,scope=unsuffixed
              type=gha,scope=linux-amd64
              type=gha,scope=linux-arm64          
            cache-to: type=gha,mode=max,scope=unsuffixed
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            
        - name: Create Dockerfile-unit
          run: |
            cp Dockerfile Dockerfile-unit
            cat files/unit/unit.Dockerfile.snippet.txt >> Dockerfile-unit
        - name: Extract Dockerfile-unit metadata
          id: metaUnit
          uses: docker/metadata-action@v5.5.1
          with:
            tags: |
               type=raw,value=${{ env.PHP_VERSION }}-unit
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Dockerfile-unit
          uses: docker/build-push-action@v5.1.0
          with:
            context: .
            file: Dockerfile-unit
            platforms: linux/amd64,linux/arm64
            provenance: false
            cache-from: |
              type=gha,scope=unsuffixed
              type=gha,scope=linux-amd64
              type=gha,scope=linux-arm64
            cache-to: type=gha,mode=max,scope=unit
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.metaUnit.outputs.tags }}
            labels: ${{ steps.metaUnit.outputs.labels }}
        - name: Create Dockerfile-fpm
          run: |
            cp Dockerfile Dockerfile-fpm
            cat files/fpm/fpm.Dockerfile.snippet.txt >> Dockerfile-fpm
        - name: Extract Dockerfile-fpm metadata
          id: metaFpm
          uses: docker/metadata-action@v5.5.1
          with:
            tags: |
               type=raw,value=${{ env.PHP_VERSION }}-fpm
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Dockerfile-fpm
          uses: docker/build-push-action@v5.1.0
          with:
            context: .
            file: Dockerfile-fpm
            platforms: linux/amd64,linux/arm64
            provenance: false
            cache-from: |
              type=gha,scope=unsuffixed
              type=gha,scope=linux-amd64
              type=gha,scope=linux-arm64
            cache-to: type=gha,mode=max,scope=fpm
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.metaFpm.outputs.tags }}
            labels: ${{ steps.metaFpm.outputs.labels }}
        - name: Create Dockerfile-apache2
          run: |
            cp Dockerfile Dockerfile-apache2
            cat files/apache2/apache2.Dockerfile.snippet.txt >> Dockerfile-apache2
        - name: Extract Dockerfile-apache2 metadata
          id: metaApache2
          uses: docker/metadata-action@v5.5.1
          with:
            tags: |
               type=raw,value=${{ env.PHP_VERSION }}-apache2
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Dockerfile-apache2
          uses: docker/build-push-action@v5.1.0
          with:
            context: .
            file: Dockerfile-apache2
            platforms: linux/amd64,linux/arm64
            provenance: false
            cache-from: |
              type=gha,scope=unsuffixed
              type=gha,scope=linux-amd64
              type=gha,scope=linux-arm64
            cache-to: type=gha,mode=max,scope=apache2
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.metaApache2.outputs.tags }}
            labels: ${{ steps.metaApache2.outputs.labels }}
        - name: Create Dockerfile-frankenphp
          run: |
            cp Dockerfile Dockerfile-frankenphp
            cat files/frankenphp/frankenphp.Dockerfile.snippet.txt >> Dockerfile-frankenphp
        - name: Extract Dockerfile-frankenphp metadata
          id: metaFrankenphp
          uses: docker/metadata-action@v5.5.1
          with:
            tags: |
               type=raw,value=${{ env.PHP_VERSION }}-frankenphp
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Dockerfile-frankenphp
          uses: docker/build-push-action@v5.1.0
          with:
            context: .
            file: Dockerfile-frankenphp
            platforms: linux/amd64,linux/arm64
            provenance: false
            cache-from: |
              type=gha,scope=unsuffixed
              type=gha,scope=linux-amd64
              type=gha,scope=linux-arm64
            cache-to: type=gha,mode=max,scope=frankenphp
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.metaFrankenphp.outputs.tags }}
            labels: ${{ steps.metaFrankenphp.outputs.labels }}
